name: Deploy WAR to EC2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      # create directory on EC2 first
      - name: Create deploy folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/ec2-user/deploy-temp

      - name: Copy WAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/*.war"
          target: "/home/ec2-user/deploy-temp"

      - name: Deploy WAR and Restart Tomcat
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            TOMCAT_DIR=/opt/tomcat

            WAR_FILE=$(ls /home/ec2-user/deploy-temp/*.war | head -n 1)

            # Stop Tomcat
            if pgrep -f 'org.apache.catalina.startup.Bootstrap' > /dev/null; then
              sudo $TOMCAT_DIR/bin/shutdown.sh
              sleep 10
            fi

            # Remove old app
            sudo rm -rf $TOMCAT_DIR/webapps/ROOT
            sudo rm -f $TOMCAT_DIR/webapps/ROOT.war

            # Deploy new WAR
            sudo mv $WAR_FILE $TOMCAT_DIR/webapps/ROOT.war

            # Start Tomcat
            sudo $TOMCAT_DIR/bin/startup.sh

            # cleanup
            rm -f /home/ec2-user/deploy-temp/*.war
